### ISSUE TITLE
Help-Fenster

### ISSUE THREAD

**Issue by Mathis-Z** [hpi-swa-teaching/SqueakShortcutConfiguration#5]
"Als Squeak-Benutzer oder Squeak-Dev will ich im ShortcutBrowser einen help-text angezeigt bekommen können, der die Funktionsweise des Shortcut-Systems erklärt"

Den help-button hat Jann schon übernommen, der funktioniert aber noch nicht.

**Comment by Computerdores** [comment]
Für Squeak Nutzer fertig, fehlt nur noch Erklärung für selbst einbinden

**Comment by Computerdores** [comment]
> fehlt nur noch Erklärung für selbst einbinden

Es muss nur noch der Text ergänzt werden hierfür

**Comment by Computerdores** [comment]
help text ist fertig
