### ISSUE TITLE
Kernel-Klassen patchen

### ISSUE THREAD

**Issue by Mathis-Z** [hpi-swa-teaching/SqueakShortcutConfiguration#8]
"Als Squeak-Benutzer möchte ich die Shortcuts für Kernel-Klassen editieren können"

Dazu gehören:

- PasteUpMorph
- TextEditor
- SmalltalkEditor
- SystemWindow
- Editor

**Comment by SolusBellator** [comment]
Needs review @Mathis-Z @Computerdores
